name: Directorio deploy #Nombre al deploy
on: [push] #En que momento se dispara --- en el push
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install packages
        run: npm ci
      - name: Bundle
        run: npm run build



